name: remedium
description: fyp

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  smart_select: ^4.3.2
  gender_selector: ^1.0.6
  image_picker: ^0.6.6+5
  circular_profile_avatar: ^1.0.8
  firebase_core: ^0.3.4
  firebase_auth: ^0.8.4+4
  cloud_firestore: ^0.9.13+1
  firebase_storage: ^2.0.0
  flutter_dialogflow: ^0.1.3
  sentiment_dart: ^0.0.4

  tflite: any

  modal_progress_hud: ^0.1.3



  open_file: ^3.0.1
  custom_cupertino_date_textbox: ^0.0.5
  syncfusion_flutter_pdf: ^18.4.47-beta
  cached_network_image: ^2.2.0+1
  image_editor: ^0.7.1
  flutter_share: ^2.0.0
  extended_image: ^0.9.0
  photo_view: ^0.9.2
  gallery_saver: ^2.0.1

  bottom_bar: ^1.2.1
  draw_graph: ^1.0.0
  loading_animations: ^2.2.0
  keyboard_visibility: ^0.5.2
  bubble: ^1.1.9+1

  share:
      git:
        url: git://github.com/codenameakshay/plugins.git
        path: packages/share

  pdf: ^1.5.0
  path_provider: ^1.6.5
  flutter_full_pdf_viewer: ^1.0.6



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  http: ^0.12.1

#dependency_overrides:
  image: ^2.1.19
  #syncfusion_flutter_pdf: ^18.4.47-beta

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/images/undraw_Chat_bot_re_e2gj.png
    - assets/images/diagnosis.png
    - assets/images/mobile_testing.png
    - assets/images/DifferentialDiagnosis.png
    - assets/images/chatbot_data_collect.jpg
    - assets/images/boat.png
    - assets/images/glacier.jpg
    - assets/images/sign_in.jpg
    - assets/images/mask.jpg
    - assets/images/doctor.jpg
    - assets/images/doctor1.jpg
    - assets/images/patient.jpg
    - assets/images/patient1.jpg
    - assets/images/doctor_inventory.jpg
    - assets/images/patient_inventory.jpg
    - assets/images/consultation.jpg
    - assets/images/consultation1.jpg
    - assets/images/jarvis.jpg
    - assets/model_unquant.tflite
    - assets/labels.txt
    - assets/high-lacing-314823-897963b2458d.json
    - assets/jarvis-kseo-0e7ecfbc60c8.json
    - assets/bot.png
    - assets/user.png
    - assets/Normal-chest-X-ray-CXR.png
  #fonts:
  #- family: Pacifico
   # fonts:
    #- asset: fonts/Pacifico-Regular.ttf

  #- family: Source Sans Pro
   # fonts:
    #- asset: fonts/SourceSansPro-Regular.ttf


  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
